// <auto-generated />
using System;
using Customer.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Customer.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201221004104_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Customer.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateOfJoin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberType")
                        .HasColumnType("int");

                    b.Property<int>("StoreID")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 100,
                            DateOfJoin = new DateTime(1980, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bugs.Bunny@dns.com",
                            FirstName = "Bugs",
                            Image = "images/bugs.png",
                            LastName = "Bunny",
                            MemberType = 0,
                            StoreID = 1
                        },
                        new
                        {
                            CustomerID = 200,
                            DateOfJoin = new DateTime(1981, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Winnie.Pooh@dns.com",
                            FirstName = "Winnie",
                            Image = "images/winnie.png",
                            LastName = "Pooh",
                            MemberType = 2,
                            StoreID = 2
                        },
                        new
                        {
                            CustomerID = 300,
                            DateOfJoin = new DateTime(1979, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mickey.Mouse@dns.com",
                            FirstName = "Mickey",
                            Image = "images/mickey.png",
                            LastName = "Mouse",
                            MemberType = 1,
                            StoreID = 3
                        },
                        new
                        {
                            CustomerID = 400,
                            DateOfJoin = new DateTime(1982, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Donald.Duck@dns.com",
                            FirstName = "Donald",
                            Image = "images/donald.png",
                            LastName = "Duck",
                            MemberType = 0,
                            StoreID = 4
                        });
                });

            modelBuilder.Entity("Customer.Models.Store", b =>
                {
                    b.Property<int>("StoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreID");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreID = 1,
                            StoreName = "TXIRV"
                        },
                        new
                        {
                            StoreID = 2,
                            StoreName = "WIMAD"
                        },
                        new
                        {
                            StoreID = 3,
                            StoreName = "NEBEL"
                        },
                        new
                        {
                            StoreID = 4,
                            StoreName = "TXDFW"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
